export const MYSQL_CHOICE_QUESTIONS = [
  { type: "choice", category: "mysql", question: "MySQL 中查看当前实例所有数据库应使用哪条语句？", options: ["SHOW TABLES;", "SHOW DATABASES;", "LIST DATABASES;", "SELECT DATABASES;"], answer: 1, explain: "SHOW DATABASES; 用于列出当前账号可访问的数据库。" },
  { type: "choice", category: "mysql", question: "切换当前会话默认数据库的语句是？", options: ["OPEN db;", "CHANGE db;", "USE db;", "SET DB db;"], answer: 2, explain: "USE 数据库名; 用于切换当前使用的数据库。" },
  { type: "choice", category: "mysql", question: "查看当前数据库中所有表的语句是？", options: ["SHOW TABLES;", "LIST TABLES;", "DESC TABLES;", "SHOW COLUMNS;"], answer: 0, explain: "SHOW TABLES; 用于查看当前库中的表列表。" },
  { type: "choice", category: "mysql", question: "查看 students 表结构最常用的语句是？", options: ["SHOW students;", "DESCRIBE students;", "SELECT * FROM students;", "CHECK TABLE students;"], answer: 1, explain: "DESCRIBE 或 DESC 可查看表结构。" },
  { type: "choice", category: "mysql", question: "下面哪条语句用于新建数据库？", options: ["NEW DATABASE training;", "CREATE DATABASE training;", "ADD DATABASE training;", "BUILD DATABASE training;"], answer: 1, explain: "CREATE DATABASE 是标准建库语句。" },
  { type: "choice", category: "mysql", question: "下面哪条语句用于新建数据表？", options: ["CREATE TABLE students (...);", "NEW TABLE students (...);", "MAKE TABLE students (...);", "INSERT TABLE students (...);"], answer: 0, explain: "CREATE TABLE 用于创建表结构。" },
  { type: "choice", category: "mysql", question: "PRIMARY KEY 的主要作用是？", options: ["允许重复", "唯一标识每一行数据", "给字段排序", "自动加密"], answer: 1, explain: "主键要求唯一且通常不为空，用于唯一标识记录。" },
  { type: "choice", category: "mysql", question: "AUTO_INCREMENT 常用于哪类字段？", options: ["主键编号", "备注字段", "日期字段", "密码字段"], answer: 0, explain: "AUTO_INCREMENT 常用于整数主键，实现自动递增编号。" },
  { type: "choice", category: "mysql", question: "VARCHAR(50) 最适合存储什么？", options: ["图片文件", "变长文本字符串", "布尔值", "整型主键"], answer: 1, explain: "VARCHAR 用于存储长度可变的字符串。" },
  { type: "choice", category: "mysql", question: "INT 类型最适合存储什么？", options: ["短文本", "日期", "整数数值", "JSON 对象"], answer: 2, explain: "INT 用于整型数值，如 id、score、count 等。" },
  { type: "choice", category: "mysql", question: "向表中新增一条记录应使用？", options: ["UPDATE", "INSERT INTO", "ALTER TABLE", "SELECT"], answer: 1, explain: "INSERT INTO 用于插入新记录。" },
  { type: "choice", category: "mysql", question: "修改表中已有记录的语句是？", options: ["MODIFY", "INSERT", "UPDATE", "CHANGE"], answer: 2, explain: "UPDATE 用于更新已有记录。" },
  { type: "choice", category: "mysql", question: "删除表中部分记录的语句是？", options: ["REMOVE", "DELETE FROM", "DROP", "TRUNCATE COLUMN"], answer: 1, explain: "DELETE FROM ... WHERE ... 用于按条件删除记录。" },
  { type: "choice", category: "mysql", question: "查询整张表的标准语句是？", options: ["SELECT * FROM students;", "GET * FROM students;", "SHOW * students;", "READ students;"], answer: 0, explain: "SELECT * FROM 表名; 用于查询全部列和全部行。" },
  { type: "choice", category: "mysql", question: "只查询 students 表中的 name 与 score 字段，应使用？", options: ["SELECT name, score FROM students;", "SELECT (name score) FROM students;", "SHOW name score FROM students;", "GET name score IN students;"], answer: 0, explain: "SELECT 可按需列出需要的字段。" },
  { type: "choice", category: "mysql", question: "WHERE 子句的主要作用是？", options: ["排序结果", "限制查询或更新范围", "创建索引", "切换数据库"], answer: 1, explain: "WHERE 用于指定条件，缩小作用范围。" },
  { type: "choice", category: "mysql", question: "按 score 从高到低排序使用哪条子句？", options: ["GROUP BY score DESC", "ORDER BY score DESC", "LIMIT score DESC", "SORT score DESC"], answer: 1, explain: "ORDER BY score DESC 表示按 score 降序排列。" },
  { type: "choice", category: "mysql", question: "LIMIT 10 的作用是？", options: ["限制返回 10 行", "删除 10 行", "更新 10 行", "按 10 排序"], answer: 0, explain: "LIMIT 用于控制返回记录数量。" },
  { type: "choice", category: "mysql", question: "统计 students 表总记录数最常用的是？", options: ["SUM(*)", "COUNT(*)", "TOTAL(*)", "NUM(*)"], answer: 1, explain: "COUNT(*) 用于统计记录条数。" },
  { type: "choice", category: "mysql", question: "查询分数大于等于 90 的学生应使用哪个条件？", options: ["score => 90", "score >= 90", "score == 90+", "score more 90"], answer: 1, explain: "MySQL 中大于等于使用 >= 运算符。" },
  { type: "choice", category: "mysql", question: "LIKE '%sql%' 最常用于？", options: ["模糊匹配字符串", "数值求和", "创建索引", "删除空值"], answer: 0, explain: "LIKE 配合 % 可进行模糊匹配。" },
  { type: "choice", category: "mysql", question: "IS NULL 用于判断什么？", options: ["字段值是否为空值 NULL", "字段是否为空字符串", "表是否不存在", "主键是否重复"], answer: 0, explain: "IS NULL 判断字段是否为数据库中的 NULL。" },
  { type: "choice", category: "mysql", question: "下面哪条语句会给 students 表新增 email 字段？", options: ["UPDATE students ADD email VARCHAR(100);", "ALTER TABLE students ADD COLUMN email VARCHAR(100);", "CREATE COLUMN email IN students;", "MODIFY students email VARCHAR(100);"], answer: 1, explain: "新增字段应使用 ALTER TABLE ... ADD COLUMN ..." },
  { type: "choice", category: "mysql", question: "删除整张表结构和数据应使用？", options: ["DELETE TABLE students;", "DROP TABLE students;", "REMOVE students;", "TRUNCATE COLUMN students;"], answer: 1, explain: "DROP TABLE 会删除表结构及其数据。" },
  { type: "choice", category: "mysql", question: "清空表数据但保留表结构常用？", options: ["DROP TABLE", "DELETE DATABASE", "TRUNCATE TABLE", "ALTER TABLE CLEAR"], answer: 2, explain: "TRUNCATE TABLE 会清空数据但保留表结构。" },
  { type: "choice", category: "mysql", question: "JOIN 的核心作用是？", options: ["删除重复行", "把多张表按关联条件组合查询", "给字段重命名", "自动创建索引"], answer: 1, explain: "JOIN 是关系型数据库多表关联查询的核心语法。" },
  { type: "choice", category: "mysql", question: "LEFT JOIN 的特点是？", options: ["只返回右表数据", "优先保留左表全部记录", "只返回匹配成功的数据", "只能用于三表查询"], answer: 1, explain: "LEFT JOIN 会保留左表全部记录，右表不匹配时填 NULL。" },
  { type: "choice", category: "mysql", question: "GROUP BY 的主要用途是？", options: ["分组聚合统计", "删除分组数据", "修改字段类型", "创建视图"], answer: 0, explain: "GROUP BY 通常配合 COUNT、SUM、AVG 等聚合函数使用。" },
  { type: "choice", category: "mysql", question: "AVG(score) 的作用是？", options: ["求最大值", "求最小值", "求平均值", "求总行数"], answer: 2, explain: "AVG 是求平均值的聚合函数。" },
  { type: "choice", category: "mysql", question: "COUNT(*), SUM(), MAX() 这类函数统称为？", options: ["窗口函数", "聚合函数", "约束函数", "逻辑函数"], answer: 1, explain: "这类对多行进行汇总计算的函数称为聚合函数。" },
  { type: "choice", category: "mysql", question: "UNIQUE 约束的作用是？", options: ["允许重复", "保证字段值唯一", "自动排序", "自动加索引并允许任意重复"], answer: 1, explain: "UNIQUE 用于保证某列或某组列不重复。" },
  { type: "choice", category: "mysql", question: "NOT NULL 约束表示？", options: ["字段不能为空", "字段必须是数字", "字段必须唯一", "字段自动增长"], answer: 0, explain: "NOT NULL 要求该字段必须有值。" },
  { type: "choice", category: "mysql", question: "DEFAULT 关键字的作用是？", options: ["删除默认值", "指定字段默认值", "设置主键", "设置排序规则"], answer: 1, explain: "DEFAULT 可为字段设置默认值。" },
  { type: "choice", category: "mysql", question: "索引最主要的价值是？", options: ["减少字段数量", "提高查询速度", "自动修复数据", "避免写入"], answer: 1, explain: "索引的核心价值是提升查询效率。" },
  { type: "choice", category: "mysql", question: "事务的主要目的之一是？", options: ["提升 UI 体验", "保证一组操作要么都成功要么都失败", "生成索引", "减少表数量"], answer: 1, explain: "事务用于保证操作的原子性与一致性。" },
  { type: "choice", category: "mysql", question: "提交事务的语句是？", options: ["SAVE;", "PUSH;", "COMMIT;", "END;"], answer: 2, explain: "COMMIT 用于提交事务。" },
  { type: "choice", category: "mysql", question: "回滚事务的语句是？", options: ["ROLLBACK;", "UNDO;", "REVERT;", "RESTORE;"], answer: 0, explain: "ROLLBACK 用于撤销未提交事务中的修改。" },
  { type: "choice", category: "mysql", question: "在更新或删除时省略 WHERE 的风险是？", options: ["语法更快", "可能影响整张表", "只影响一行", "自动进入事务"], answer: 1, explain: "省略 WHERE 往往会更新或删除整表数据。" },
  { type: "choice", category: "mysql", question: "查看当前使用的数据库可以执行？", options: ["SELECT DB();", "SELECT DATABASE();", "SHOW CURRENT DB;", "GET DATABASE();"], answer: 1, explain: "DATABASE() 函数返回当前会话使用的数据库名。" },
  { type: "choice", category: "mysql", question: "字符集 utf8mb4 的推荐场景是？", options: ["仅英文库", "支持更完整的 Unicode 字符", "只能存图片", "只用于索引"], answer: 1, explain: "utf8mb4 能更完整地支持 Unicode，包括 emoji 等字符。" }
] as const

export const MYSQL_TRUE_FALSE_QUESTIONS = [
  { type: "truefalse", category: "mysql", question: "SHOW TABLES; 用于查看当前数据库中的所有表。", answer: true, explain: "正确。SHOW TABLES; 会列出当前数据库中的表。" },
  { type: "truefalse", category: "mysql", question: "USE training; 会删除 training 数据库。", answer: false, explain: "错误。USE 只是切换当前数据库，不会删除数据。" },
  { type: "truefalse", category: "mysql", question: "PRIMARY KEY 字段可以出现重复值。", answer: false, explain: "错误。主键必须唯一。" },
  { type: "truefalse", category: "mysql", question: "VARCHAR 适合存储长度可变的文本。", answer: true, explain: "正确。VARCHAR 用于变长字符串。" },
  { type: "truefalse", category: "mysql", question: "SELECT * FROM students; 会查询 students 表中的全部列。", answer: true, explain: "正确。* 表示全部列。" },
  { type: "truefalse", category: "mysql", question: "UPDATE 语句通常应配合 WHERE 使用。", answer: true, explain: "正确。这样可以避免误更新整张表。" },
  { type: "truefalse", category: "mysql", question: "DELETE FROM students; 只会删除一条记录。", answer: false, explain: "错误。没有 WHERE 时会删除整张表的所有记录。" },
  { type: "truefalse", category: "mysql", question: "ALTER TABLE 可用于新增字段。", answer: true, explain: "正确。ALTER TABLE ... ADD COLUMN ... 可新增字段。" },
  { type: "truefalse", category: "mysql", question: "DROP TABLE 会保留数据，只删除索引。", answer: false, explain: "错误。DROP TABLE 会删除整个表结构和数据。" },
  { type: "truefalse", category: "mysql", question: "JOIN 用于把多张表按条件组合查询。", answer: true, explain: "正确。JOIN 是多表关联查询的核心语法。" },
  { type: "truefalse", category: "mysql", question: "ORDER BY score DESC 表示按分数从低到高排序。", answer: false, explain: "错误。DESC 表示降序，即从高到低。" },
  { type: "truefalse", category: "mysql", question: "COUNT(*) 用于统计记录数量。", answer: true, explain: "正确。COUNT(*) 会返回符合条件的行数。" },
  { type: "truefalse", category: "mysql", question: "索引的主要作用是提高查询效率。", answer: true, explain: "正确。索引可以显著提升查询性能。" },
  { type: "truefalse", category: "mysql", question: "事务提交使用 COMMIT，撤销使用 ROLLBACK。", answer: true, explain: "正确。COMMIT 提交，ROLLBACK 回滚。" },
  { type: "truefalse", category: "mysql", question: "utf8mb4 不支持中文，只支持英文。", answer: false, explain: "错误。utf8mb4 支持完整 Unicode，自然也支持中文。" }
] as const

export const MYSQL_FILL_QUESTIONS = [
  { type: "fill", category: "mysql", question: "查看数据库列表的语句是 SHOW _____;", answer: ["DATABASES", "databases"], explain: "SHOW DATABASES; 用于查看数据库列表。" },
  { type: "fill", category: "mysql", question: "切换到 training 数据库应写成 USE _____.", answer: ["training"], explain: "USE training; 用于切换当前数据库。" },
  { type: "fill", category: "mysql", question: "查看当前数据库表列表的语句是 SHOW _____.", answer: ["TABLES", "tables"], explain: "SHOW TABLES; 用于查看当前库中的表。" },
  { type: "fill", category: "mysql", question: "查看表结构常用 DESC 或 _____ 语句。", answer: ["DESCRIBE", "describe"], explain: "DESCRIBE 与 DESC 等价。" },
  { type: "fill", category: "mysql", question: "向表中新增记录的关键字是 ____ INTO。", answer: ["INSERT", "insert"], explain: "INSERT INTO 用于插入新数据。" },
  { type: "fill", category: "mysql", question: "修改已有记录的 SQL 以 _____ 开头。", answer: ["UPDATE", "update"], explain: "UPDATE 用于更新记录。" },
  { type: "fill", category: "mysql", question: "删除记录的标准语句以 DELETE _____ 开头。", answer: ["FROM", "from"], explain: "DELETE FROM 表名 WHERE ... 是标准写法。" },
  { type: "fill", category: "mysql", question: "限制查询结果只返回 10 行，应使用 _____ 10。", answer: ["LIMIT", "limit"], explain: "LIMIT 用于限制返回结果数量。" },
  { type: "fill", category: "mysql", question: "按 score 从高到低排序，关键字应写为 ORDER BY score _____.", answer: ["DESC", "desc"], explain: "DESC 表示降序。" },
  { type: "fill", category: "mysql", question: "统计记录总数最常用的聚合函数是 _____(*).", answer: ["COUNT", "count"], explain: "COUNT(*) 是最常见的计数方式。" },
  { type: "fill", category: "mysql", question: "把多张表按条件关联查询的关键字是 _____.", answer: ["JOIN", "join"], explain: "JOIN 用于多表关联。" },
  { type: "fill", category: "mysql", question: "提交事务使用 _____; 语句。", answer: ["COMMIT", "commit"], explain: "COMMIT 用于提交事务。" },
  { type: "fill", category: "mysql", question: "撤销未提交事务使用 _____; 语句。", answer: ["ROLLBACK", "rollback"], explain: "ROLLBACK 用于回滚事务。" },
  { type: "fill", category: "mysql", question: "MySQL 中保证字段值唯一的约束之一是 _____.", answer: ["UNIQUE", "unique"], explain: "UNIQUE 约束要求字段值不能重复。" },
  { type: "fill", category: "mysql", question: "推荐支持完整 Unicode 字符集的数据库编码是 _____.", answer: ["utf8mb4"], explain: "utf8mb4 能支持更完整的字符集。" }
] as const
