import type { ScenarioData } from "./LinuxPractice";

export const MYSQL_PRACTICE_SCENARIOS: ScenarioData[] = [
  {
    id: 41,
    title: "连接 MySQL 与查看数据库",
    description: "学习连接 MySQL 客户端、查看数据库列表并切换数据库",
    difficulty: "简单",
    category: "mysql",
    tasks: [
      {
        prompt: "使用 root 用户连接本地 MySQL 客户端",
        successMsg: "✓ 已写出连接命令！",
        hint: "mysql -u root -p",
        explanationOnCorrect: "mysql -u root -p 是最常见的连接方式，-u 指定用户名，-p 表示输入密码。",
        explanationOnWrong: "连接 MySQL 时，通常使用 mysql -u 用户名 -p 的格式。",
        category: "mysql",
        validation: {
          type: "command",
          startsWith: "mysql",
          contains: ["-u", "root", "-p"],
        },
      },
      {
        prompt: "写出查看当前实例所有数据库的 SQL",
        successMsg: "✓ 数据库列表查询正确！",
        hint: "SHOW DATABASES;",
        explanationOnCorrect: "SHOW DATABASES 用于列出当前账号可见的数据库列表。",
        explanationOnWrong: "查看数据库列表使用 SHOW DATABASES; 语句。",
        category: "mysql",
        validation: {
          type: "command",
          startsWith: "SHOW",
          contains: ["DATABASES"],
        },
      },
      {
        prompt: "切换到 training 数据库",
        successMsg: "✓ 已切换数据库语句！",
        hint: "USE training;",
        explanationOnCorrect: "USE 用于切换当前会话默认数据库，后续查询可直接写表名。",
        explanationOnWrong: "切换数据库使用 USE 数据库名; 的语法。",
        category: "mysql",
        validation: {
          type: "command",
          startsWith: "USE",
          contains: ["training"],
        },
      },
    ],
  },
  {
    id: 42,
    title: "设计表结构",
    description: "学习建表、查看表结构和修改字段",
    difficulty: "中等",
    category: "mysql",
    tasks: [
      {
        prompt: "创建一张 students 表，包含 id 主键自增和 name 字段",
        successMsg: "✓ 建表语句结构正确！",
        hint: "CREATE TABLE students (...);",
        explanationOnCorrect: "CREATE TABLE 定义表结构时，应优先确定主键、自增和核心字段类型。",
        explanationOnWrong: "请使用 CREATE TABLE students (...) 语法，并包含 id 与 name 字段。",
        category: "mysql",
        validation: {
          type: "command",
          startsWith: "CREATE TABLE",
          contains: ["students", "id", "AUTO_INCREMENT", "PRIMARY KEY", "name"],
        },
      },
      {
        prompt: "查看 students 表结构",
        successMsg: "✓ 表结构查看语句正确！",
        hint: "DESC students;",
        explanationOnCorrect: "DESC 或 DESCRIBE 都可以查看表结构，是排查字段定义的常用方式。",
        explanationOnWrong: "查看表结构可使用 DESC students; 或 DESCRIBE students;",
        category: "mysql",
        validation: {
          type: "command",
          startsWith: "DESC",
          contains: ["students"],
        },
      },
      {
        prompt: "给 students 表新增 email 字段",
        successMsg: "✓ 表结构修改语句正确！",
        hint: "ALTER TABLE students ADD COLUMN email VARCHAR(100);",
        explanationOnCorrect: "ALTER TABLE 让我们在保留原表数据的前提下演进结构。",
        explanationOnWrong: "新增字段通常写成 ALTER TABLE 表名 ADD COLUMN 字段名 类型;",
        category: "mysql",
        validation: {
          type: "command",
          startsWith: "ALTER TABLE",
          contains: ["students", "ADD", "email"],
        },
      },
    ],
  },
  {
    id: 43,
    title: "常用数据操作",
    description: "练习查询、新增、更新和删除语句的基本写法",
    difficulty: "中等",
    category: "mysql",
    tasks: [
      {
        prompt: "查询 students 表中的全部数据",
        successMsg: "✓ 查询语句正确！",
        hint: "SELECT * FROM students;",
        explanationOnCorrect: "SELECT 是最核心的查询语句，* 表示返回全部列。",
        explanationOnWrong: "查询整张表使用 SELECT * FROM 表名;",
        category: "mysql",
        validation: {
          type: "command",
          startsWith: "SELECT",
          contains: ["FROM", "students"],
        },
      },
      {
        prompt: "向 students 表插入一条 name 为 Alice、score 为 95 的记录",
        successMsg: "✓ 插入语句正确！",
        hint: "INSERT INTO students (name, score) VALUES ('Alice', 95);",
        explanationOnCorrect: "INSERT INTO 用于新增记录，列和值的顺序必须保持一致。",
        explanationOnWrong: "请使用 INSERT INTO 表名 (列...) VALUES (值...); 格式。",
        category: "mysql",
        validation: {
          type: "command",
          startsWith: "INSERT INTO",
          contains: ["students", "name", "score", "Alice", "95"],
        },
      },
      {
        prompt: "把 id=1 的学生成绩更新为 100",
        successMsg: "✓ 更新语句正确！",
        hint: "UPDATE students SET score = 100 WHERE id = 1;",
        explanationOnCorrect: "UPDATE 配合 WHERE 能精确修改目标记录，避免误更新整表。",
        explanationOnWrong: "更新数据请使用 UPDATE 表名 SET 字段=值 WHERE 条件;",
        category: "mysql",
        validation: {
          type: "command",
          startsWith: "UPDATE",
          contains: ["students", "SET", "score", "100", "WHERE", "id", "1"],
        },
      },
      {
        prompt: "删除 id=3 的学生记录",
        successMsg: "✓ 删除语句正确！",
        hint: "DELETE FROM students WHERE id = 3;",
        explanationOnCorrect: "DELETE 必须谨慎使用 WHERE 条件，否则会删除整张表的数据。",
        explanationOnWrong: "删除记录请使用 DELETE FROM 表名 WHERE 条件;",
        category: "mysql",
        validation: {
          type: "command",
          startsWith: "DELETE FROM",
          contains: ["students", "WHERE", "id", "3"],
        },
      },
    ],
  },
]
